"""create weather schema

Revision ID: a574fad5bb40
Revises: 
Create Date: 2025-05-18 22:46:09.017342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a574fad5bb40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('location_name', sa.String(length=100), nullable=False),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.Column('sunrise', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precipitation_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_id', sa.Integer(), nullable=False),
    sa.Column('pressure_mb', sa.Float(), nullable=False),
    sa.Column('pressure_in', sa.Float(), nullable=False),
    sa.Column('precip_mm', sa.Float(), nullable=False),
    sa.Column('precip_in', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Integer(), nullable=False),
    sa.Column('cloud', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['weather_id'], ['weather.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wind_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weather_id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.Integer(), nullable=False),
    sa.Column('kph', sa.Float(), nullable=False),
    sa.Column('direction', sa.Enum('N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW', name='winddirectionenum'), nullable=False),
    sa.Column('go_out', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['weather_id'], ['weather.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wind_data')
    op.drop_table('precipitation_data')
    op.drop_table('weather')
    # ### end Alembic commands ###
